PR - Iris Disbursement API
Midtrans/midtrans-java pull request #7
Opened 2020-05-13 07:15 UTC by Xaxxis

New feature:
- API Iris disbursement
- Payment BIN API
- Set Connection Pool & Keep alive connection
- Set header X-Idempotency-key for Iris and Idempotency-Key for Payment
- Set `X-Append-Notification`: to add new notification url(s) alongside the settings on dashboard
- Set `X-Override-Notification`: to use new notification url(s) disregarding the settings on dashboard
- Library version on `User-Agent` header

Improvement:

- Change logic for setup headers
- Remove versioning path from base URL, move to `String API_VERSION` in CoreAPI, SnapAPI interface class
- Improve conditional logic for HttpLoggingInterceptors. Now all debugging response handle only from HttpLoggingInterceptors Which can show logs request and response information

Bugs fix:
- Failure/error response from Midtrans api is empty json.

2020-05-26 09:22 UTC, rizdaprasetya requested changes
This is technical feedback, readme related feedback ill be submitted separately

2020-05-26 09:22 UTC, rizdaprasetya commented on library/pom.xml
> +            <url>https://api.bintray.com/maven/midtrans/midtrans-java/com.midtrans/;publish=1</url>
indentation looks not consistent

2020-05-26 09:22 UTC, rizdaprasetya commented on library/src/main/java/com/midtrans/Config.java
> +    private String irisMerchantKey;
Why is it different from `SERVER_KEY` to `irisMerchantKey`? not  uppercase?

2020-05-26 09:22 UTC, rizdaprasetya commented on library/src/main/java/com/midtrans/service/MidtransIrisApi.java
> +    JSONObject getListBank() throws MidtransError;
change to more descriptive `getBeneficiaryBanks`

2020-05-26 09:22 UTC, rizdaprasetya commented on library/src/main/java/com/midtrans/service/MidtransIrisApi.java
> +    JSONObject getPayoutsDetails(String referenceNo) throws MidtransError;
`getPayoutDetails` payout without `s`

2020-05-26 09:22 UTC, rizdaprasetya commented on library/src/main/java/com/midtrans/service/MidtransIrisApi.java
> +    JSONArray getListBeneficiaries() throws MidtransError;
change to `getBeneficiaries`

2020-05-26 09:22 UTC, rizdaprasetya commented on library/src/main/java/com/midtrans/service/MidtransIrisApi.java
> +    JSONObject getAggregatorBalance() throws MidtransError;
change to `getBalance`

2020-05-26 09:48 UTC, rizdaprasetya requested changes
Feedback for readme related

2020-05-26 09:48 UTC, rizdaprasetya commented on CHANGELOG.md
> +- Improve conditional logic for HttpLoggingInterceptors. Now all debugging response handle only from HttpLoggingInterceptors Which can show logs request and response information
`will be handled only from`

2020-05-26 09:48 UTC, rizdaprasetya commented on CHANGELOG.md
> +- Failure/error response from Midtrans api is empty json.
`Midtrans api result in empty json`

2020-05-26 09:48 UTC, rizdaprasetya commented on CHANGELOG.md
> +HttpLoggingInterceptor: Which can show logs request and response information. This feature auto disable when using production mode.
This feature is disabled by default on production mode.

2020-05-26 09:48 UTC, rizdaprasetya commented on CHANGELOG.md
> +- Can set writeTimeout
- Allow HTTP Proxy config
- Allow set connectionTimeout
- Allow set readTimeout
- Allow set writeTimeout

2020-05-26 09:48 UTC, rizdaprasetya commented on README.md
> +You can also re-setting config using `apiConfig()` method on MidtransCoreApi.Class, MidtransSnapApi.Class or MidtransIrisApi.class like `coreApi.apiConfig.set( ... )`
can also re-set config

2020-05-26 09:48 UTC, rizdaprasetya commented on README.md
> +In production environment, LOG is automatically turn off, if you want enable LOG, you can `setEnabledLog` like this
`LOG is by default turned off`
`you can enable by setEnabledLog, e.g:`

2020-05-26 09:48 UTC, rizdaprasetya commented on README.md
> +You can see some Iris API examples [here](example/src/main/java/com/midtrans/sample/controller/IrisController.java).
remove `some`

2020-05-26 09:48 UTC, rizdaprasetya commented on library/src/main/java/com/midtrans/service/MidtransIrisApi.java
> +     * Do re-setting config Class iris-credential, IrisIdempotencyKey
`re-set config Class`

2020-05-27 02:19 UTC, Xaxxis commented on library/pom.xml
> +            <url>https://api.bintray.com/maven/midtrans/midtrans-java/com.midtrans/;publish=1</url>
done

2020-05-27 07:47 UTC, rizdaprasetya approved these changes
Looks good now! please merge and release! Thanks @Xaxxis

2020-05-27 14:13 UTC, merged